// <auto-generated />
using GameCatalogue.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCatalogue.API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameCatalogue.API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo",
                            Genre = "Action-Adventure",
                            Platform = "Nintendo Switch",
                            ReleaseYear = 2017,
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "FromSoftware",
                            Genre = "Action RPG",
                            Platform = "PC / PS5 / Xbox Series X",
                            ReleaseYear = 2022,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Rockstar Games",
                            Genre = "Action-Adventure",
                            Platform = "PC / PS4 / Xbox One",
                            ReleaseYear = 2018,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "Supergiant Games",
                            Genre = "Roguelike",
                            Platform = "PC / Nintendo Switch",
                            ReleaseYear = 2020,
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "CD Projekt Red",
                            Genre = "Action RPG",
                            Platform = "PC / PS5 / Xbox Series X",
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
